name: .NET + SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests and collect coverage
      run: |
        dotnet test NetSdrClientAppTests/NetSdrClientAppTests.csproj \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:CoverletOutput=coverage.opencover.xml

    - name: Begin SonarCloud Analysis
      run: |
        dotnet sonarscanner begin \
          /k:"LeVanchua_-" \
          /o:"levanchua" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.projectBaseDir="./NetSdrClientApp" \
          /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml"

    - name: Build
      run: dotnet build NetSdrClientApp/NetSdrClientApp.csproj --no-restore

    - name: End SonarCloud Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
